--1 . what is the revenue generated by the male vs female customers 

SELECT gender ,SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender

--2. what is the customers used a discount but still spent more than the average purchase amount ?

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount)FROM customer)

-- 3 . which are the top 10 products with the highest average review rating ?

SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as "average product rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 10

-- 4 . compare the avg purchase amount between the standard and express shipping ? 

SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type

-- 5. Do subscribers spend the most? comapare the average spend and total revenue between the subscribers and non subscribers ?

SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend,total_revenue DESC

-- 6. which 5 products have the highest percentage of purchases with discounts applied ? 

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7. Divide the customers into new, returning, and loyal customers based on their total number 
--of the previous buying and show thw count of the each segment.

WITH customer_type as (
SELECT customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer
)

SELECT customer_segment, COUNT(*) as "Number of customers"
FROM customer_type
GROUP BY customer_segment

-- 8. what is the top 5  most purchased products from each category ?

WITH item_counts as (
SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC ) as item_rank
FROM customer
GROUP BY category , item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 5;

-- 9. are customers who are repeat buyers (more than previous puchases) also likely to subscribe ?

SELECT subscription_status,
count(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10 . what is the revenue contribution of each age group ?

SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;